### ISSUE TITLE
Please push to CRAN

### ISSUE THREAD

**Issue by mattdowle** [arnaldpuy/sensobol#1]
Hi Arnald,
Thanks for using data.table!  I'm working on releasing 1.12.4 to CRAN and have checked all packages using data.table on CRAN.  Your package `sensobol` is affected.
However, the good news is you've already fixed it.
The error is : 
```
* checking re-building of vignette outputs ... WARNING
Error(s) in re-building vignettes:
  ...
--- re-building ‘sensobol.Rmd’ using rmarkdown
Quitting from lines 100-121 (sensobol.Rmd) 
Error: processing vignette 'sensobol.Rmd' failed with diagnostics:
Supplied 200 items to be assigned to 100 items of column 'sensitivity'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
--- failed re-building ‘sensobol.Rmd’

SUMMARY: processing the following file failed:
  ‘sensobol.Rmd’
```

But this is because of this (old) line : 

```
tmp1 <- b.rep[1:k, lapply(V1, function(x) x[["t"]])][
  , sensitivity:= rep(c("Si", "STi"), each = R)
  ]
```

At that point, each `x` was a 2-column matrix (100x2) and data.table 1.12.2 treated each matrix as if it were a 200 long single vector.   The new version data.table 1.12.4 creates columns for each of the matrix columns, hence the assignment length error later on.

I was going to suggest changing `function(x) x[["t"]]` to `function(x) as.vector(x[["t"]])`.   But when I tried to create a PR to do that, I then saw you've already changed/fixed that part in dev.  I checked it works with the new data.table version.

Please can you publish to CRAN?  Otherwise when I publish data.table,  it will cause `sensobol` to fail.

Thanks, Matt

**Comment by arnaldpuy** [comment]
Thanks for reaching out Matt! Will push the package to CRAN today. All the best!

**Comment by arnaldpuy** [comment]
On its way to CRAN. thanks again.

**Comment by mattdowle** [comment]
Fantastic. Thanks, @arnaldpuy !
