### ISSUE TITLE
How to incorporate the package with models that run outside R?

### ISSUE THREAD

**Issue by wenlong-liu** [arnaldpuy/sensobol#2]
Dear Arnald,

Thank you for your excellent work. This package is awesome and very useful.

I have a quick question regarding the use of sensobol with models that are not running in R.  Many models were written in Fortran (legacy models).  Would you please inform me of using sensobol with those models?

Thank you.
Wenlong

**Comment by arnaldpuy** [comment]
Hi Wenlong Liu,

Thanks for you nice email. 

At the moment sensobol does not integrate with Fortran. But if you have a model written in fortran, you can do the following:

- Construct the sampling matrix with sobol_matrices(), and then export it to .csv.
- Run the model in fortran in each row of the sampling matrix, and then retrieve the vector output.
- Load the output vector in r and proceed to sensitivity analysis as usual.

Hope this helps and sorry for the delay in getting back to you.

Yours,

Arnald

**Comment by wenlong-liu** [comment]
Hi Arnald,

Thank you for your kind reply. I will try the workflow.  Have a nice day.

Best,
Wenlong
