### ISSUE TITLE
How can one check for convergence in sensitivity indices?

### ISSUE THREAD

**Issue by CMDiebold** [arnaldpuy/sensobol#3]
Dear Arnald,

firstly: thank you for this great package! It is very helpful and intuitive to use. 

I have a question regarding the convergence of the computed sensitivity indices. 
In order to analyze whether the computed sensitivity indices are independent of the sample size, one might want to re-run _sobol_indices_ using sub-samples of decreasing size extracted from the original sample. This is especially the case if the model is computationally expensive to run, and one does not want to compute an entirely new sample matrix and implied model output for each sample size. 
Could you advise me on how to realize this? Please consider this code (https://stackoverflow.com/q/67704751/16037300?sem=2) as an example of the encountered issue.

Thank you!

Best wishes,
Céline

**Comment by arnaldpuy** [comment]
Dear Céline,

Thanks a lot for reaching out, and I am very glad you find the package helpful!
Is it OK if I get back to you on this issue in a few days? I am absolutely backlogged at the moment.
Thanks for your understanding.

All best,

A.

**Comment by arnaldpuy** [comment]
Ok Céline, check this file out – it should do what you require. Let me know!

All best,

Arnald
[code_celine.md](https://github.com/arnaldpuy/sensobol/files/6548682/code_celine.md)

**Comment by CMDiebold** [comment]
Hi Arnald,

Thank you so much for finding a solution so quickly! I find sensitivity analysis quite interesting, but obviously this was not an emergency :D 

Your code works perfectly! 
I just added a bit to not only estimate the sensitivity indices but also their bootstrapping confidence intervals, for the different sample sizes. I find this actually quite insightful when plotting the sensitivity indices together with their confidence intervals against the sample size. This is also advised in the literature, e.g. Sarrazin et al. (2016, p. 144) conclude: “It is worth noting that an apparent convergence of the bootstrap mean of the sensitivity index (flattening of the line) is a necessary but not sufficient condition for convergence. It can happen that the bootstrap mean takes similar values in two different samples ‘by chance’ while the actual statistical convergence is not reached yet (the confidence intervals are still very wide). Therefore, it is important to also include information about the confidence intervals.”
Thank you for your swift and great response!

Best wishes and have a good evening,
Best wishes,
Céline


Source: Fanny Sarrazin, Francesca Pianosi, Thorsten Wagener, Global Sensitivity Analysis of environmental models: Convergence and validation, Environmental Modelling & Software, Volume 79, 2016, Pages 135-152, ISSN 1364-8152, https://doi.org/10.1016/j.envsoft.2016.02.005.

**Comment by arnaldpuy** [comment]
Glad to hear that!
All best,

A.
