### ISSUE TITLE
`sobol_matrices` fails gracelessly when provided a single value for `params`

### ISSUE THREAD

**Issue by Patrick330** [arnaldpuy/sensobol#8]
The function `sobol_matrices()` fails when the `params` argument is passed a single value. 

For example:  
```sensobol::sobol_matrices(N = 1000, params = 'one')```

Returns: 
> Error in rbind(A, B, C, out) : number of columns of matrices must match (see arg 4)

The cause is this line in function `scrambled_sobol()`, which returns a vector when `X` has only one column, instead of a matrix as it usually does. 
```AB <- X[(2 * N + 1):nrow(X), ]```

Adding `drop = FALSE` to this line will fix it:
```AB <- X[(2 * N + 1):nrow(X), , drop = FALSE]```

Alternately, the code could catch this situation and return a more informative error message.

**Comment by arnaldpuy** [comment]
Dear Patrick,
Thanks for the heads-up –will include the line in the new release.
A.
